sylius_newsletter_backend_newsletter:
    resource: @SyliusNewsletterBundle/Resources/config/routing/backend/newsletter.yml
    prefix: /administration/newsletters

sylius_newsletter_backend_subscriber:
    resource: @SyliusNewsletterBundle/Resources/config/routing/backend/subscriber.yml
    prefix: /administration/subscribers

sylius_newsletter_subscriber:
    resource: @SyliusNewsletterBundle/Resources/config/routing/frontend/subscriber.yml
    prefix: /newsletter
