sylius_sandbox_core_frontend:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.frontend:indexAction }
    
sylius_sandbox_core_backend:
    pattern: /administration
    defaults: { _controller: sylius_sandbox_core.controller.backend:indexAction }
    