# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

imports:
    - { resource: dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: %sylius.database.name%_testing

security:
    firewalls:
        main:
            remember_me: false
