language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --no-scripts

script: phpunit --coverage-text -c sandbox/

notifications:
  email:
    - travis-ci@sylius.org
