language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --coverage-text -c sylius-sandbox/

notifications:
  email:
    - travis-ci@sylius.org

