# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sylius_sandbox_core_backend:
    pattern: /
    defaults: { _controller: sylius_sandbox_core.controller.backend.main:indexAction }

sylius_sandbox_backend_address:
    prefix: /addresses
    resource: @SandboxCoreBundle/Resources/config/routing/backend/address.yml
