# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

imports:
    - { resource: includes/parameters.yml }
    - { resource: includes/security.yml }
    - { resource: includes/database.yml }

framework:
    default_locale: %locale%
    form: ~
    charset:       UTF-8
    secret: %secret%
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/base.yml" }
    validation:    { enabled: true }
    translator:    { fallback: %locale% }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SESSION
        lifetime: 72000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug% 
    
swiftmailer:
    disable_delivery: true

sylius_assortment:
    driver: ORM
    classes:
        model:
            product:  Application\Bundle\AssortmentBundle\Entity\Product
        form:
            type:
                product: Application\Bundle\AssortmentBundle\Form\Type\ProductFormType

sylius_catalog:
    driver: ORM
    catalogs:
        assortment:
            mode: S
            property: "products"
            sorter: sylius_assortment.sorting
            classes:
                model: Application\Bundle\AssortmentBundle\Entity\Category
            templates:
                backend:
                    list: ApplicationAssortmentBundle:Backend/Category:list.html.twig
                    show: ApplicationAssortmentBundle:Backend/Category:show.html.twig
                    create: ApplicationAssortmentBundle:Backend/Category:create.html.twig
                    update: ApplicationAssortmentBundle:Backend/Category:update.html.twig
                frontend:
                    list: ApplicationAssortmentBundle:Frontend/Category:list.html.twig
                    show: ApplicationAssortmentBundle:Frontend/Category:show.html.twig
                    
sylius_newsletter:
    driver: ORM
    classes:
        model:
            newsletter: Sylius\Bundle\NewsletterBundle\Entity\DefaultNewsletter
            subscriber: Sylius\Bundle\NewsletterBundle\Entity\DefaultSubscriber
    extensions:
        confirmation:
            enabled: true
            options:
                email:
                    from: no-reply@example.com
                    subject: "Confirm your subscription on example.com!"
                    template: ApplicationNewsletterBundle:Confirmation:email.html.twig
                    
sylius_cart:
    driver: ORM
    engine: twig
    operator: app_cart.operator
    classes:
        model:
            cart: Application\Bundle\CartBundle\Entity\Cart
            item: Application\Bundle\CartBundle\Entity\Item
        form:
           type:
               item: Application\Bundle\CartBundle\Form\Type\ItemType
