# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

imports:
    - { resource: base.yml }

framework:
    router:        { resource: "%kernel.root_dir%/config/routing/installer.yml" }
    
sylius_cart:
    freeze: true
